# Travis CI (MIT License) configuration file for the Underscores WordPress theme.
# @link https://travis-ci.org/

# For use with the Underscores WordPress theme.
# @link https://github.com/Automattic/_s

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: node_js
node_js:
  - "0.12"

before_script:
  - bower install
  - gulp
  - gulp release

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false
